[tool.poetry]
name = "jrnl"
version = "2.0.0"
description = "Collect your thoughts and notes without leaving the command line."
authors = [
    "Manuel Ebert <manuel@1450.me>",
    "Jonathan Wren",
    "Micah Ellison"
]
license = "MIT"
readme = "README.md"
homepage = "https://jrnl.sh"
repository = "https://github.com/jrnl-org/jrnl"

[tool.poetry.dependencies]
python = "^2.7.9"
pyxdg = "^0.26.0"
cryptography = "^2.7"
passlib = "^1.7"
parsedatetime = ">=1.5"
keyring = [
    {version = "<=18.0", python = "^2.7"},
    {version = "^19.0", python = "^3.3"}
]
python-dateutil = [
    {version = "<=1.5", python = "^2.7"},
    {version = "^2.2", python = "^3.3"}
]
pytz = "^2019.1"
tzlocal = "^1.5"
asteval = "^0.9.14"
colorama = {version = "^0.4.1",platform = "win32"}

[tool.poetry.dev-dependencies]
behave = "^1.2"
mkdocs = "^1.0"

[tool.poetry.scripts]
jrnl = 'jrnl:cli.run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

